### ISSUE TITLE
Error...

### ISSUE THREAD

**Issue by s3ng1r** [lambsteak/auto-pixel-canvas#1]
Traceback (most recent call last):
  File "auto_pixel.py", line 402, in <module>
    db=get_confs()
  File "auto_pixel.py", line 250, in get_confs
    input('>>>')
  File "<string>", line 0

![capturar](https://user-images.githubusercontent.com/29692428/27518262-2ecfaa26-59b2-11e7-90fd-cfd28e4676eb.PNG)

**Comment by lambsteak** [comment]
Hmm, could you send me the log file (notebook.logs.notebook)?

**Comment by s3ng1r** [comment]
[notebook.logs.zip](https://github.com/lambsteak/auto-pixel-canvas/files/1102328/notebook.logs.zip)

thx

**Comment by lambsteak** [comment]
Are you using python3? Or python2?
Because the code is written in python3 and input() in python2 is equivalent to eval() in python3

**Comment by s3ng1r** [comment]
Python 2

Em Seg, 26 de jun de 2017 16:31, Param Prabhakar <notifications@github.com>
escreveu:

**Comment by lambsteak** [comment]
Python3 is needed to run this code. Try with python3 and see if it works.
