### ISSUE TITLE
Error after paiting the first point

### ISSUE THREAD

**Issue by Lucas-Uchiha** [lambsteak/auto-pixel-canvas#3]
After paiting the first point I receive this error:
[img](http://i.imgur.com/kMGMdaq.png)
Then the program still running but doesn't make any action.
My OS is Windows 10, and I'm using the Windows executable provided by you.

**Comment by lambsteak** [comment]
Can you send me the log file (notebook.logs.notebook)?

**Comment by Lucas-Uchiha** [comment]
I changed the extension to .txt because github won't accept other.
[notebook.logs.notebook.txt](https://github.com/lambsteak/auto-pixel-canvas/files/1117912/notebook.logs.notebook.txt)

**Comment by lambsteak** [comment]
Yeah got the log file. Damn it was a minor bug but I fixed it. I've updated the source code, will also update the windows executable as soon as I switch my OS to Windows. Do tell me if there are any more issues with the program!

**Comment by Lucas-Uchiha** [comment]
Thanks.

**Comment by lambsteak** [comment]
Hey! I updated the Windows executable, follow the link in README file.

**Comment by Lucas-Uchiha** [comment]
Yep, now it's working properly. Thanks very much!
